/* tslint:disable */
/* eslint-disable */
/**
 * MedChain API
 * API for Healthy-Stellar health donor protocol
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';


/**
 * AccessApi - axios parameter creator
 */
export const AccessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Grant record access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accessGrantPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/access/grant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccessApi - functional programming interface
 */
export const AccessApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccessApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Grant record access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accessGrantPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accessGrantPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessApi.accessGrantPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccessApi - factory interface
 */
export const AccessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccessApiFp(configuration)
    return {
        /**
         * 
         * @summary Grant record access
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accessGrantPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accessGrantPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccessApi - interface
 */
export interface AccessApiInterface {
    /**
     * 
     * @summary Grant record access
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    accessGrantPost(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AccessApi - object-oriented interface
 */
export class AccessApi extends BaseAPI implements AccessApiInterface {
    /**
     * 
     * @summary Grant record access
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accessGrantPost(options?: RawAxiosRequestConfig) {
        return AccessApiFp(this.configuration).accessGrantPost(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary User login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authLoginPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 */
export interface AuthApiInterface {
    /**
     * 
     * @summary User login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authLoginPost(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * 
     * @summary User login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLoginPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RecordsApi - axios parameter creator
 */
export const RecordsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all health records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/records`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload a health record
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordsPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/records`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecordsApi - functional programming interface
 */
export const RecordsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecordsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all health records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecordsApi.recordsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload a health record
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordsPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordsPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecordsApi.recordsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecordsApi - factory interface
 */
export const RecordsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecordsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all health records
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.recordsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload a health record
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordsPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.recordsPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecordsApi - interface
 */
export interface RecordsApiInterface {
    /**
     * 
     * @summary Get all health records
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recordsGet(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Upload a health record
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recordsPost(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * RecordsApi - object-oriented interface
 */
export class RecordsApi extends BaseAPI implements RecordsApiInterface {
    /**
     * 
     * @summary Get all health records
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recordsGet(options?: RawAxiosRequestConfig) {
        return RecordsApiFp(this.configuration).recordsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload a health record
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recordsPost(options?: RawAxiosRequestConfig) {
        return RecordsApiFp(this.configuration).recordsPost(options).then((request) => request(this.axios, this.basePath));
    }
}



